// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entity "ai-notetaking-be/internal/entity"
	database "ai-notetaking-be/pkg/database"
	context "context"

	interfaces "ai-notetaking-be/internal/interfaces"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// INotebookRepository is an autogenerated mock type for the INotebookRepository type
type INotebookRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, notebook
func (_m *INotebookRepository) Create(ctx context.Context, notebook *entity.Notebook) error {
	ret := _m.Called(ctx, notebook)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Notebook) error); ok {
		r0 = rf(ctx, notebook)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *INotebookRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: cxt
func (_m *INotebookRepository) GetAll(cxt context.Context) ([]*entity.Notebook, error) {
	ret := _m.Called(cxt)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*entity.Notebook
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*entity.Notebook, error)); ok {
		return rf(cxt)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*entity.Notebook); ok {
		r0 = rf(cxt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Notebook)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(cxt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *INotebookRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.Notebook, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Notebook
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Notebook, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Notebook); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Notebook)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NullifyParentById provides a mock function with given fields: ctx, id
func (_m *INotebookRepository) NullifyParentById(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for NullifyParentById")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateByID provides a mock function with given fields: ctx, notebook
func (_m *INotebookRepository) UpdateByID(ctx context.Context, notebook *entity.Notebook) error {
	ret := _m.Called(ctx, notebook)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Notebook) error); ok {
		r0 = rf(ctx, notebook)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateParentID provides a mock function with given fields: ctx, id, parentID
func (_m *INotebookRepository) UpdateParentID(ctx context.Context, id uuid.UUID, parentID *uuid.UUID) error {
	ret := _m.Called(ctx, id, parentID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateParentID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *uuid.UUID) error); ok {
		r0 = rf(ctx, id, parentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UsingTx provides a mock function with given fields: ctx, tx
func (_m *INotebookRepository) UsingTx(ctx context.Context, tx database.DatabaseQueryer) interfaces.INotebookRepository {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for UsingTx")
	}

	var r0 interfaces.INotebookRepository
	if rf, ok := ret.Get(0).(func(context.Context, database.DatabaseQueryer) interfaces.INotebookRepository); ok {
		r0 = rf(ctx, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.INotebookRepository)
		}
	}

	return r0
}

// NewINotebookRepository creates a new instance of INotebookRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewINotebookRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *INotebookRepository {
	mock := &INotebookRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
